/*
  Static Web Apps Module — CoolTech Credential Manager
  =====================================================
  Provisions:
    - Azure Static Web Apps (Free tier)
    - Hosts the React/Vite frontend SPA

  The frontend GitHub Actions workflow is auto-generated by Azure when you
  link a GitHub repository in the portal. After provisioning via Bicep,
  run the portal linking step to connect GitHub and generate the workflow.

  Alternatively, use the Azure CLI:
    az staticwebapp create \
      --name <name> \
      --resource-group <rg> \
      --source https://github.com/<org>/<repo> \
      --branch main \
      --app-location ./frontend \
      --output-location dist \
      --login-with-github
*/

param staticWebAppName string
param location string
param backendApiUrl string

// ─── Static Web App ───────────────────────────────────────────────────────────

resource staticWebApp 'Microsoft.Web/staticSites@2023-01-01' = {
  name: staticWebAppName
  location: location
  sku: {
    name: 'Free'
    tier: 'Free'
  }
  properties: {
    // stagingEnvironmentPolicy: 'Enabled' // Uncomment to enable PR preview environments
    allowConfigFileUpdates: true
    enterpriseGradeCdnStatus: 'Disabled'
  }
}

// ─── App Settings (Build-time environment variables) ─────────────────────────
// VITE_API_URL is injected at build time by the GitHub Actions workflow.
// Setting it here registers it in Azure; the workflow reads it automatically.

resource staticWebAppSettings 'Microsoft.Web/staticSites/config@2023-01-01' = {
  parent: staticWebApp
  name: 'appsettings'
  properties: {
    VITE_API_URL: backendApiUrl
  }
}

// ─── Outputs ──────────────────────────────────────────────────────────────────

output staticWebAppUrl string = 'https://${staticWebApp.properties.defaultHostname}'
output staticWebAppId string = staticWebApp.id

// ─── Post-deploy steps ────────────────────────────────────────────────────────
// 1. Link GitHub repository via portal or az staticwebapp create --source
// 2. Copy the deployment token and save as GitHub secret:
//    AZURE_STATIC_WEB_APPS_API_TOKEN_<name>
// 3. Update App Service FRONTEND_URL to match the staticWebAppUrl output
